#!/usr/bin/env python3
"""Bundle FLE's runtime-injected Lua into a Factorio MOD (control.lua).

FLE normally injects all tool functions + event handlers at runtime via RCON.
A spectator client that joins the live server never sees those injections, so
its script state mismatches the server -> "script-event-mismatch" desync, and
the join-save crashes because functions stored in `storage` can't be
serialized. The fix is to ship the SAME functions + event registrations as a
mod that the server AND every client load identically at startup (deterministic
lockstep), with functions in _G (fle_actions/fle_utils) so storage stays
serializable.

This bundler concatenates the FLE Lua in the order the env loads it, applies
the storage.actions->fle_actions / storage.utils->fle_utils / storage.get_alerts
->fle_get_alerts transform, wraps each source file in an IIFE (some init mods
are modules ending in `return`; the leading `;` avoids Lua's ambiguous-syntax
trap), relocates the chunk-level storage-data writes into on_init, and appends
a remote interface ('fle') so RCON / other contexts can call the functions
(mod-env globals are not visible to /silent-command).

Run: `python build_mod.py` (from anywhere). Output: ./fle_tools/control.lua.
Then zip the fle_tools/ folder as fle_tools_<version>.zip (UNZIPPED mods get
checksum 0 and fail MP matching) and place it in both the server's and the
spectator client's mod directory. The client must also disable the DLC
(elevated-rails/quality/space-age) in its mod-list to match the DLC-stripped
FLE server.
"""

from pathlib import Path

HERE = Path(__file__).resolve().parent
FLE_ENV = HERE.parent.parent / "env"  # fle/env
OUT = HERE / "fle_tools" / "control.lua"

# Init mods, in the order instance.py loads them. checksum.lua is FLE's
# RCON-cache mechanism, not game logic -> skip it.
INIT_MODS = [
    "initialise",
    "lualib_util",
    "serialize",
    "serialize_direction_fix",
    "connection_points",
    "recipe_fluid_connection_mappings",
    "utils",
    "alerts",
]

# Chunk-level storage-DATA statements that must NOT run at mod chunk-load
# (storage is nil there). score's one-time init needs game access, so it is
# left to FLE's RCON setup (touches only serializable storage data).
STRIP_CHUNK_LINES = [
    "storage.alerts = {}",
    "storage.crafting_queue = {}",
    "storage.goal = nil",
]
STRIP_PREFIXES = (
    "storage.initial_harvested_value",
    "storage.initial_crafted_net_value",
    "local scores = production_score.get_production_scores()",
)


def transform(src: str) -> str:
    src = src.replace("storage.actions", "fle_actions")
    src = src.replace("storage.utils", "fle_utils")
    src = src.replace("storage.get_alerts", "fle_get_alerts")
    return src


def strip_chunk_data(src: str) -> str:
    out = []
    for line in src.splitlines():
        s = line.strip()
        if s in STRIP_CHUNK_LINES or s.startswith(STRIP_PREFIXES):
            out.append(f"-- [fle_tools: relocated to on_init] {s}")
        else:
            out.append(line)
    return "\n".join(out)


def load_tool_files() -> list[Path]:
    files: list[Path] = []
    for tool_dir in sorted(p for p in (FLE_ENV / "tools").glob("*/*") if p.is_dir()):
        files.extend(sorted(tool_dir.glob("*.lua"), key=lambda x: x.name.endswith("server.lua")))
    return files


def main() -> None:
    parts = [
        "-- AUTO-GENERATED by build_mod.py. FLE tool functions + event handlers,\n"
        "-- bundled into a mod so server and spectator load them identically.\n"
        "fle_actions = fle_actions or {}\nfle_utils = fle_utils or {}\n",
        "local function fle_init_storage()\n"
        "  storage.actions = storage.actions or {}\n"
        "  storage.utils = storage.utils or {}\n"
        "  storage.initial_score = storage.initial_score or {[\"player\"]=0}\n"
        "  storage.alerts = storage.alerts or {}\n"
        "  storage.elapsed_ticks = storage.elapsed_ticks or 0\n"
        "  storage.fast = storage.fast or false\n"
        "  storage.agent_characters = storage.agent_characters or {}\n"
        "  storage.paths = storage.paths or {}\n"
        "  storage.path_requests = storage.path_requests or {}\n"
        "  storage.harvested_items = storage.harvested_items or {}\n"
        "  storage.crafted_items = storage.crafted_items or {}\n"
        "  storage.walking_queues = storage.walking_queues or {}\n"
        "  storage.crafting_queue = storage.crafting_queue or {}\n"
        "  storage.debug = storage.debug or { rendering = false }\n"
        "end\nscript.on_init(fle_init_storage)\n",
    ]

    sources: list[tuple[str, str]] = []
    for name in INIT_MODS:
        f = FLE_ENV / "mods" / f"{name}.lua"
        if f.exists():
            sources.append((f"mods/{name}.lua", f.read_text()))
    for f in load_tool_files():
        sources.append((f"tools/{f.relative_to(FLE_ENV / 'tools')}", f.read_text()))

    for label, src in sources:
        body = strip_chunk_data(transform(src))
        # Leading `;` is REQUIRED: without it Lua merges this `(function()...)`
        # with the previous statement (ambiguous-syntax -> "call a nil value").
        parts.append(f"\n-- ===== {label} =====\n;(function()\n{body}\nend)()\n")

    # Mod-env globals are invisible to RCON /silent-command; expose via a remote
    # interface (lockstep-safe: remote.call runs on every peer).
    parts.append(
        "\n-- ===== fle remote interface (RCON entry point) =====\n"
        ";remote.add_interface('fle', {\n"
        "  action = function(name, ...) return fle_actions[name](...) end,\n"
        "  util = function(name, ...) return fle_utils[name](...) end,\n"
        "  get_alerts = function(...) return fle_get_alerts(...) end,\n"
        "  has = function(name) return fle_actions[name] ~= nil end,\n"
        "  set_storage = function(k, v) storage[k] = v end,\n"
        "})\n"
    )

    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(sources)} files)")


if __name__ == "__main__":
    main()
